name: Testing
on: push

jobs:
  test_project:
    runs-on: windows-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Run django unit tests
      run:
        python -m pip install –upgrade pip
        pip install --user django
        python manage.py test